### ISSUE TITLE
RN Appbuiilder / Web support?

### ISSUE THREAD

**Issue by gwhizoftv** [EkaanshArora/Agora-RN-VirtualBackground#1]
Hi E! Can you make this work for RN Appbuilder also ? If we want to use with Appbuilder, what changes do we need ?
Many thanks @EkaanshArora

**Comment by EkaanshArora** [comment]
AppBuilder uses the React Native SDK for Android and iOS, and the Web SDK for the web release. You'd need to modify the source code to call the `engine.enableVirtualBackground(true, virtualSource)` and the [equivalent web method](https://docs-preprod.agora.io/en/Interactive%20Broadcast/virtual_background_web_ng?platform=Web) before joining the call. You can also make a feature request in the repo.

**Comment by gwhizoftv** [comment]
@EkaanshArora thank you for this info. I checked the article for the Web SDK here: https://docs-preprod.agora.io/en/Interactive%20Broadcast/virtual_background_web_ng?platform=Web It doesn't mention engine.enableVirtualBackground(true, virtualSource) , do we need to add this to the article ?

**Comment by EkaanshArora** [comment]
`engine.enableVirtualBackground(true, virtualSource)` is for React Native SDK that's used on Android and iOS, for Web follow the documentation to load the WASM module and call the required functions.
